name: Update Index

on:
  push:
    branches: [ master ]
    paths:
      - '**.tgz'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true  # This is true by default, but good to be explicit.
      - name: Helm Installation
        uses: azure/setup-helm@v1.1
        with:
          version: v3.7.0
      - name: Update Index
        run: |
          helm repo index .
          git config --global user.email "opensonaproject@gmail.com"
          git config --global user.name "edgestack-bot"
          git add index.yaml
          git commit -m "Update chart index"
          # Update the remote URL to include the token
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git push
